export const Matches_1 = [
    {
        id:1,
        match_id:1,
        first_name:"Arda Kardeşler",
        age :34,
        birthdate:"03.01.1988",        
        image: "1.jpg", 
        match_count: "8",
        rating:"473",
        Yellow_Card:29,
        Red_Card:1,
        Penalty:2,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"The son of former Bursaspor national goalkeeper Eser Kardeşler, Arda Kardeşler is also the brother of goalkeeper Erce Kardeşler. He started his refereeing career in 2009. He made his professional debut on September 1, 2013. He has been in the Süper Lig since the 2015-2016 season."
    },
    {
        id:2,
        match_id:1,
        first_name:"Volkan Bayarslan",
        age:44, 
        birthdate:"01.01.1978",
        image: "2.jpg", 
        match_count: "7",
        rating:"343",
        Yellow_Card:26,
        Red_Card:0,
        Penalty:2,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Volkan Bayarslan (born 1 January 1978, Erzurum) Turkish referee. He played in the Bursaspor - Manisaspor match for the first time in the Super League. He played football in Erzurumspor's youth team. He was transferred to Ağrı Spor when he was in the 3rd year of Karadeniz Technical University. He quit professional football in 1999 and started refereeing. Later, 37-year-old Bayarslan, who moved to Istanbul with his family, successfully rose in the classification with the contribution of his strong physical structure and football knowledge, and started to manage matches in the Super League. "
    },
    {
        id:3,
        match_id:1,
        first_name:"Yaşar Kemal Uğurlu",
        age:41,
        birthdate:"1981",
        image: "3.jpg", 
        match_count: "7",
        rating:"563",
        Yellow_Card:37,
        Red_Card:0,
        Penalty:5,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Yaşar Kemal Uğurlu was born in Ankara in 1981. He started his refereeing career in 2004 with the refereeing course he attended in Düzce in 2002. Uğurlu, who plays football in various categories of the Ankaragücü team, is a graduate of Gazi University, department of economics. Yaşar Kemal Uğurlu decided to become a referee after he did not like the referee's decisions after watching a match."
    },
    {
        id:4,
        match_id:1,
        first_name:"Mert Güzenge",
        age:31,
        birthdate:"1990", 
        image: "4.jpeg", 
        match_count:"7", 
        rating:"435",
        Yellow_Card:29,
        Red_Card:0,
        Penalty:1,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",        
        info:"Mert Güzenge, from Istanbul, is the top-class referee. Mert Güzenge, whose main profession is a manager, also continues to act as a referee."
    },
    {
        id:5,
        match_id:1,
        first_name:"Abdulkadir Bitigen",
        age:39,
        birthdate:"12.02.1983",
        image: "5.jpg", 
        match_count: "6",
        rating:"647",
        Yellow_Card:31,
        Red_Card:1,
        Penalty:2,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"He started refereeing in 2007. The first match he directed in the Super League was Eskişehirspor - Konyaspor (2014). His father, Galip Bitigen, was also a football referee."
    },
    {
        id:6,
        match_id:1,
        first_name:"Umit Öztürk",
        age:39,
        birthdate:"1983", 
        image: "6.jpg", 
        match_count: "6",
        rating:"536",
        Yellow_Card:33,
        Red_Card:0,
        Penalty:4,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Referee Ümit Öztürk was born in the Şişli district of Istanbul in 1983. Originally from Ordu, the 39-year-old referee studied geological engineering at Karadeniz Technical University. He decided to become a referee in his last year of university."
    },
    {
        id:7,
        match_id:1,
        first_name:"Bahattin Şimşek",
        age:32,
        birthdate:"1988",
        image: "7.jpg", 
        match_count: "6",
        rating:"536",
        Yellow_Card:16,
        Red_Card:2,
        Penalty:0,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Bahattin Şimşek, one of the successful Turkish referees who was born in 1988, stepped into the refereeing profession in 2006. Şimşek, who managed his first professional match on September 9, 2012, is a graduate of Adnan Menderes University, School of Physical Education and Sports."
    },
    {
        id:8,
        match_id:1,
        first_name:"Mustafa Kürşad Filiz",
        age:29,
        birthdate:"1993",
        image: "8.jpg", 
        match_count: "6",
        rating:"874",
        Yellow_Card:24,
        Red_Card:0,
        Penalty:1,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Mustafa Kürşat Filiz is an Istanbul regional referee, born in 1993. He whistled in 96 matches in total."
    },
    {
        id:9,
        match_id:1,
        first_name:"Kadir Sağlam",
        age:35,
        birthdate:"1987",
        image: "9.jpg", 
        match_count: "6",
        rating:"876",
        Yellow_Card:31,
        Red_Card:1,
        Penalty:3,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Kadir Sağlam, born in 1987, is the Ankara regional referee. He took part in 130 matches in total. Kadir Sağlam, who usually serves as the 4th referee, started playing as the middle referee last year."
    },
    {
        id:10,
        match_id:1,
        first_name:"Ali Şansalan",
        age:34,
        birthdate:"17.03.1988",
        image: "10.jpg", 
        match_count: "6",
        rating:"765",
        Yellow_Card:36,
        Red_Card:0,
        Penalty:6,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Ali Şansalan (born 17 March 1988, Balıkesir) is a Turkish professional football referee in the Süper Lig. He graduated from Çanakkale Onsekiz Mart University Faculty of Sports Sciences in 2010. He started refereeing in 2009 as a Çanakkale regional referee while he was still a university student. In the fight between Akhisar Belediyespor and Kardemir Karabükspor in 2017, Şansalan has been playing a regular role in the Super League since 2019, leading the game for the first time in the Super League."
    },
    {
        id:11,
        match_id:1,
        first_name:"Atilla Karaoğlan",
        age:36,
        birthdate:"22.06.1986",
        image: "11.jpg", 
        match_count: "6",
        rating:"985",
        Yellow_Card:26,
        Red_Card:0,
        Penalty:2,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"He was born on June 22, 1986 in Sakarya. Atilla Karaoğlan, who started his refereeing career in 2007, has been managing matches in the Super League since the 2019-2020 season."
    },
    {
        id:12,
        match_id:1,
        first_name:"Zorbay Küçük",
        age:30,
        birthdate:"14.09.1992",
        image: "12.jpg", 
        match_count: "6",
        rating:"985",
        Yellow_Card:26,
        Red_Card:0,
        Penalty:2,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Zorbay Küçük was born in Adana on October 18, 1992. Zorbay Küçük is the son of former football player and coach Feyzullah Küçük. He started refereeing in 2010."
    },
    {
        id:13,
        match_id:1,
        first_name:"Hüseyin Göcek",
        age:45,
        birthdate:"30.11.1976",
        image: "13.jpg", 
        match_count: "5",
        rating:"785",
        Yellow_Card:30,
        Red_Card:0,
        Penalty:1,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Assigned by UEFA in high-level competitions, he served as the 4th referee in the fight between Greece and Russia, which is one of the Euro 2012 group qualifying matches, as the line referee in the fights between Ireland-Italy, Ukraine-Sweden and Spain-Portugal in the semi-finals. Hüseyin Göçek managed the 2014 Turkish Cup Final, played on 7 May 2014 between Galatasaray and Eskişehirspor.[5] With this match, he was appointed as the cup final referee for the first time. Before the 2015-16 season, Turkish Football Federation signed a professional contract for the first time with 9 referees, including Göçek"
    },
    {
        id:14,
        match_id:1,
        first_name:"Suat Arslanboğa",
        age:44,
        birthdate:"04.06.1978",
        image: "14.jpg", 
        match_count: "5", 
        rating:"985",
        Yellow_Card:33,
        Red_Card:0,
        Penalty:2,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"He started as an assistant referee in the away league in 2001. In the Super League, he played his first match in the Bursaspor - Hacettepe match on October 6, 2007. In this match, he showed 6 players from Bursaspor and 2 players from Hacettepespor a yellow card and a red card to İlhan Eker from Hacettepespor. The match ended 1-1 with mutual goals from Mustafa Sarp and Bülent Kocabey."
    },
    {
        id:15,
        match_id:1,
        first_name:"Mete Kalkavan",
        age:42,
        birthdate:"1980",
        image: "15.jpg", 
        match_count: "5", 
        rating:"985",
        Yellow_Card:19,
        Red_Card:2,
        Penalty:3,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Mete Kalkavan is a Turkish football referee and mechanical engineer. He graduated with a successful degree in the TFF Refereeing course he attended. His first match in 1999 was the Istanbulspor - Altay match played as the 1st assistant referee in the PAF League. He still serves as the Super League referee. 24 December He earned the right to wear a FIFA badge in 2012. He signed a professional contract for the first time with 9 referees, including Turkish Football Federation Kalkavan, before the 2015-16 season. He resigned from refereeing on March 9, 2022 and returned to refereeing on May 1, 2022."
    },
    {
        id:16,
        match_id:1,
        first_name:"Ali Palabıyık",
        age:41,
        birthdate:"14.08.1981",
        image: "16.jpg", 
        match_count: "5", 
        rating:"476",
        Yellow_Card:24,
        Red_Card:5,
        Penalty:6,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Ali Palabıyık (born 14 August 1981, Ankara) is a Turkish football referee with FIFA license. He was among the referees who will wear the FIFA badge announced for 2015 for the first time. Before the 2015-16 season, Turkish Football Federation signed a professional contract for the first time with 9 referees, including Palabiyik."
    },
    {
        id:17,
        match_id:1,
        first_name:"Sarper Barış Saka",
        age:39,
        birthdate:"24.10.1983",
        image: "17.jpg", 
        match_count: "5", 
        rating:"235",
        Yellow_Card:22,
        Red_Card:1,
        Penalty:0,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Sarper Barış Saka was born in Antalya in 1983, he is the Ankara regional referee. He took part in 129 matches in total."
    },
    {
        id:18,
        match_id:1,
        first_name:"Çağdaş Altay",
        age:"-",
        birthdate:"-",
        image: "18.jpg", 
        match_count: "5", 
        rating:"647",
        Yellow_Card:21,
        Red_Card:2,
        Penalty:3,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Contemporary Altay is the Istanbul regional referee. He took part in 112 matches in total."
    },
    {
        id:19,
        match_id:1,
        first_name:"Tugay Kaan Numanoğlu",
        age:37,
        birthdate:"06.11.1985",
        image: "19.jpg", 
        match_count: "4", 
        rating:"758",
        Yellow_Card:17,
        Red_Card:1,
        Penalty:2,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Referee Tugay Kaan Numanoğlu, born on November 6, 1985, is 37 years old today. He started his refereeing career in 2006 when he was 21 years old. Tugay Kaan Numanoğlu, who started to manage the Super League matches in 2020, was involved in various matches of the lower leagues before that."
    },
    {
        id:20,
        match_id:1,
        first_name:"Halil Umut Beler",
        age:36,
        birthdate:"01.08.1986",
        image: "20.jpg", 
        match_count: "4", 
        rating:"875",
        Yellow_Card:24,
        Red_Card:0,
        Penalty:0,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Halil Umut Meler is a Turkish football referee. He has been FIFA listed since 2017 and a member of the UEFA Elite since 2022. He has officiated in 2017–18 UEFA Europa League, beginning with the match between Vojvodina and Ružomberok on 29 June 2017 "
    },
    {
        id:21,
        match_id:1,
        first_name:"Erkan Özdamar",
        age:34,
        birthdate:"1988",
        image: "21.jpg", 
        match_count: "4", 
        rating:"875",
        Yellow_Card:24,
        Red_Card:0,
        Penalty:0,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Erkan Özdamar, who is a dance instructor, has international Sports and Dance Instructor certificates. Erkan Özdamar, one of the referees of the Ankara region of the TFF, started to be assigned as a referee in the Super League in the 2020-2021 season. Erkan Özdamar, in 15 matches he directed, 65 yellows, 1 second. He took out 2 red cards, one of the yellow ones."
    },
    {
        id:22,
        match_id:1,
        first_name:"Burak Şeker",
        age:33,
        birthdate:"1989", 
        image: "22.jpg", 
        match_count: "3", 
        rating:"675",
        Yellow_Card:15,
        Red_Card:1,
        Penalty:3,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Burak Şeker is an Antalya regional referee, born in 1989. He has taken part in 122 matches so far."
    },
    {
        id:23,
        match_id:1,
        first_name:"Yasin Kol",
        age:34,
        birthdate:"15.12.1987",
        image: "23.jpg", 
        match_count: "3", 
        rating:"766",
        Yellow_Card:13,
        Red_Card:0,
        Penalty:2,
        hometeam:"Fenerbahçe",
        againstteam:"Hatayspor",
        date:"27/20/2022",
        info:"Yasin Kol, born in Trabzon in 1987, is a Trabzon regional referee. He has taken part in 126 matches so far. The red card rate of the Super League is 0.3."
    }]
export const Matches_2 = [
        {
            id:1,
            match_id:2,
            first_name:"Arda Kardeşler",
            age :34,
            birthdate:"03.01.1988",        
            image: "1.jpg", 
            match_count: "8",
            rating:"344",
            Yellow_Card:29,
            Red_Card:1,
            Penalty:2,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"The son of former Bursaspor national goalkeeper Eser Kardeşler, Arda Kardeşler is also the brother of goalkeeper Erce Kardeşler. He started his refereeing career in 2009. He made his professional debut on September 1, 2013. He has been in the Süper Lig since the 2015-2016 season."
        },
        {
            id:2,
            match_id:2,
            first_name:"Volkan Bayarslan",
            age:44, 
            birthdate:"01.01.1978",
            image: "2.jpg", 
            match_count: "7",
            rating:"344",
            Yellow_Card:26,
            Red_Card:0,
            Penalty:2,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Volkan Bayarslan (born 1 January 1978, Erzurum) Turkish referee. He played in the Bursaspor - Manisaspor match for the first time in the Super League. He played football in Erzurumspor's youth team. He was transferred to Ağrı Spor when he was in the 3rd year of Karadeniz Technical University. He quit professional football in 1999 and started refereeing. Later, 37-year-old Bayarslan, who moved to Istanbul with his family, successfully rose in the classification with the contribution of his strong physical structure and football knowledge, and started to manage matches in the Super League. "
        },
        {
            id:3,
            match_id:2,
            first_name:"Yaşar Kemal Uğurlu",
            age:41,
            birthdate:"1981",
            image: "3.jpg", 
            match_count: "7",
            rating:"644",
            Yellow_Card:37,
            Red_Card:0,
            Penalty:5,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Yaşar Kemal Uğurlu was born in Ankara in 1981. He started his refereeing career in 2004 with the refereeing course he attended in Düzce in 2002. Uğurlu, who plays football in various categories of the Ankaragücü team, is a graduate of Gazi University, department of economics. Yaşar Kemal Uğurlu decided to become a referee after he did not like the referee's decisions after watching a match."
        },
        {
            id:4,
            match_id:2,
            first_name:"Mert Güzenge",
            age:31,
            birthdate:"1990", 
            image: "4.jpeg", 
            match_count:"7", 
            rating:"736",
            Yellow_Card:29,
            Red_Card:0,
            Penalty:1,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Mert Güzenge, from Istanbul, is the top-class referee. Mert Güzenge, whose main profession is a manager, also continues to act as a referee."
        },
        {
            id:5,
            match_id:2,
            first_name:"Abdulkadir Bitigen",
            age:39,
            birthdate:"12.02.1983",
            image: "5.jpg", 
            match_count: "6",
            rating:"394",
            Yellow_Card:31,
            Red_Card:1,
            Penalty:2,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"He started refereeing in 2007. The first match he directed in the Super League was Eskişehirspor - Konyaspor (2014). His father, Galip Bitigen, was also a football referee."
        },
        {
            id:6,
            match_id:2,
            first_name:"Umit Öztürk",
            age:39,
            birthdate:"1983", 
            image: "6.jpg", 
            match_count: "6",
            rating:"984",
            Yellow_Card:33,
            Red_Card:0,
            Penalty:4,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Referee Ümit Öztürk was born in the Şişli district of Istanbul in 1983. Originally from Ordu, the 39-year-old referee studied geological engineering at Karadeniz Technical University. He decided to become a referee in his last year of university."
        },
        {
            id:7,
            match_id:2,
            first_name:"Bahattin Şimşek",
            age:32,
            birthdate:"1988",
            image: "7.jpg", 
            match_count: "6",
            rating:"984",
            Yellow_Card:16,
            Red_Card:2,
            Penalty:0,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Bahattin Şimşek, one of the successful Turkish referees who was born in 1988, stepped into the refereeing profession in 2006. Şimşek, who managed his first professional match on September 9, 2012, is a graduate of Adnan Menderes University, School of Physical Education and Sports."
        },
        {
            id:8,
            match_id:2,
            first_name:"Mustafa Kürşad Filiz",
            age:29,
            birthdate:"1993",
            image: "8.jpg", 
            match_count: "6",
            rating:"763",
            Yellow_Card:24,
            Red_Card:0,
            Penalty:1,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Mustafa Kürşat Filiz is an Istanbul regional referee, born in 1993. He whistled in 96 matches in total."
        },
        {
            id:9,
            match_id:2,
            first_name:"Kadir Sağlam",
            age:35,
            birthdate:"1987",
            image: "9.jpg", 
            match_count: "6",
            rating:"764",
            Yellow_Card:31,
            Red_Card:1,
            Penalty:3,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Kadir Sağlam, born in 1987, is the Ankara regional referee. He took part in 130 matches in total. Kadir Sağlam, who usually serves as the 4th referee, started playing as the middle referee last year."
        },
        {
            id:10,
            match_id:2,
            first_name:"Ali Şansalan",
            age:34,
            birthdate:"17.03.1988",
            image: "10.jpg", 
            match_count: "6",
            rating:"947",
            Yellow_Card:36,
            Red_Card:0,
            Penalty:6,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Ali Şansalan (born 17 March 1988, Balıkesir) is a Turkish professional football referee in the Süper Lig. He graduated from Çanakkale Onsekiz Mart University Faculty of Sports Sciences in 2010. He started refereeing in 2009 as a Çanakkale regional referee while he was still a university student. In the fight between Akhisar Belediyespor and Kardemir Karabükspor in 2017, Şansalan has been playing a regular role in the Super League since 2019, leading the game for the first time in the Super League."
        },
        {
            id:11,
            match_id:2,
            first_name:"Atilla Karaoğlan",
            age:36,
            birthdate:"22.06.1986",
            image: "11.jpg", 
            match_count: "6",
            rating:"984",
            Yellow_Card:26,
            Red_Card:0,
            Penalty:2,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"He was born on June 22, 1986 in Sakarya. Atilla Karaoğlan, who started his refereeing career in 2007, has been managing matches in the Super League since the 2019-2020 season."
        },
        {
            id:12,
            match_id:2,
            first_name:"Zorbay Küçük",
            age:30,
            birthdate:"14.09.1992",
            image: "12.jpg", 
            match_count: "6",
            rating:"747",
            Yellow_Card:26,
            Red_Card:0,
            Penalty:2,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Zorbay Küçük was born in Adana on October 18, 1992. Zorbay Küçük is the son of former football player and coach Feyzullah Küçük. He started refereeing in 2010."
        },
        {
            id:13,
            match_id:2,
            first_name:"Hüseyin Göcek",
            age:45,
            birthdate:"30.11.1976",
            image: "13.jpg", 
            match_count: "5",
            rating:"344",
            Yellow_Card:30,
            Red_Card:0,
            Penalty:1,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Assigned by UEFA in high-level competitions, he served as the 4th referee in the fight between Greece and Russia, which is one of the Euro 2012 group qualifying matches, as the line referee in the fights between Ireland-Italy, Ukraine-Sweden and Spain-Portugal in the semi-finals. Hüseyin Göçek managed the 2014 Turkish Cup Final, played on 7 May 2014 between Galatasaray and Eskişehirspor.[5] With this match, he was appointed as the cup final referee for the first time. Before the 2015-16 season, Turkish Football Federation signed a professional contract for the first time with 9 referees, including Göçek"
        },
        {
            id:14,
            match_id:2,
            first_name:"Suat Arslanboğa",
            age:44,
            birthdate:"04.06.1978",
            image: "14.jpg", 
            match_count: "5", 
            rating:"344",
            Yellow_Card:33,
            Red_Card:0,
            Penalty:2,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"He started as an assistant referee in the away league in 2001. In the Super League, he played his first match in the Bursaspor - Hacettepe match on October 6, 2007. In this match, he showed 6 players from Bursaspor and 2 players from Hacettepespor a yellow card and a red card to İlhan Eker from Hacettepespor. The match ended 1-1 with mutual goals from Mustafa Sarp and Bülent Kocabey."
        },
        {
            id:15,
            match_id:2,
            first_name:"Mete Kalkavan",
            age:42,
            birthdate:"1980",
            image: "15.jpg", 
            match_count: "5", 
            rating:"654",
            Yellow_Card:19,
            Red_Card:2,
            Penalty:3,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Mete Kalkavan is a Turkish football referee and mechanical engineer. He graduated with a successful degree in the TFF Refereeing course he attended. His first match in 1999 was the Istanbulspor - Altay match played as the 1st assistant referee in the PAF League. He still serves as the Super League referee. 24 December He earned the right to wear a FIFA badge in 2012. He signed a professional contract for the first time with 9 referees, including Turkish Football Federation Kalkavan, before the 2015-16 season. He resigned from refereeing on March 9, 2022 and returned to refereeing on May 1, 2022."
        },
        {
            id:16,
            match_id:2,
            first_name:"Ali Palabıyık",
            age:41,
            birthdate:"14.08.1981",
            image: "16.jpg", 
            match_count: "5", 
            rating:"763",
            Yellow_Card:24,
            Red_Card:5,
            Penalty:6,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Ali Palabıyık (born 14 August 1981, Ankara) is a Turkish football referee with FIFA license. He was among the referees who will wear the FIFA badge announced for 2015 for the first time. Before the 2015-16 season, Turkish Football Federation signed a professional contract for the first time with 9 referees, including Palabiyik."
        },
        {
            id:17,
            match_id:2,
            first_name:"Sarper Barış Saka",
            age:39,
            birthdate:"24.10.1983",
            image: "17.jpg", 
            match_count: "5", 
            rating:"764",
            Yellow_Card:22,
            Red_Card:1,
            Penalty:0,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Sarper Barış Saka was born in Antalya in 1983, he is the Ankara regional referee. He took part in 129 matches in total."
        },
        {
            id:18,
            match_id:2,
            first_name:"Çağdaş Altay",
            age:"-",
            birthdate:"-",
            image: "18.jpg", 
            match_count: "5", 
            rating:"654",
            Yellow_Card:21,
            Red_Card:2,
            Penalty:3,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Contemporary Altay is the Istanbul regional referee. He took part in 112 matches in total."
        },
        {
            id:19,
            match_id:2,
            first_name:"Tugay Kaan Numanoğlu",
            age:37,
            birthdate:"06.11.1985",
            image: "19.jpg", 
            match_count: "4", 
            rating:"556",
            Yellow_Card:17,
            Red_Card:1,
            Penalty:2,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Referee Tugay Kaan Numanoğlu, born on November 6, 1985, is 37 years old today. He started his refereeing career in 2006 when he was 21 years old. Tugay Kaan Numanoğlu, who started to manage the Super League matches in 2020, was involved in various matches of the lower leagues before that."
        },
        {
            id:20,
            match_id:2,
            first_name:"Halil Umut Beler",
            age:36,
            birthdate:"01.08.1986",
            image: "20.jpg", 
            match_count: "4", 
            rating:"874",
            Yellow_Card:24,
            Red_Card:0,
            Penalty:0,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Halil Umut Meler is a Turkish football referee. He has been FIFA listed since 2017 and a member of the UEFA Elite since 2022. He has officiated in 2017–18 UEFA Europa League, beginning with the match between Vojvodina and Ružomberok on 29 June 2017 "
        },
        {
            id:21,
            match_id:2,
            first_name:"Erkan Özdamar",
            age:34,
            birthdate:"1988",
            image: "21.jpg", 
            match_count: "4", 
            rating:"376",
            Yellow_Card:24,
            Red_Card:0,
            Penalty:0,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Erkan Özdamar, who is a dance instructor, has international Sports and Dance Instructor certificates. Erkan Özdamar, one of the referees of the Ankara region of the TFF, started to be assigned as a referee in the Super League in the 2020-2021 season. Erkan Özdamar, in 15 matches he directed, 65 yellows, 1 second. He took out 2 red cards, one of the yellow ones."
        },
        {
            id:22,
            match_id:2,
            first_name:"Burak Şeker",
            age:33,
            birthdate:"1989", 
            image: "22.jpg", 
            match_count: "3", 
            rating:"746",
            Yellow_Card:15,
            Red_Card:1,
            Penalty:3,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Burak Şeker is an Antalya regional referee, born in 1989. He has taken part in 122 matches so far."
        },
        {
            id:23,
            match_id:2,
            first_name:"Yasin Kol",
            age:34,
            birthdate:"15.12.1987",
            image: "23.jpg", 
            match_count: "3", 
            rating:"646",
            Yellow_Card:13,
            Red_Card:0,
            Penalty:2,
            hometeam:"Sivasspor",
            againstteam:"Galatasaray",
            date:"29/12/2022",
            info:"Yasin Kol, born in Trabzon in 1987, is a Trabzon regional referee. He has taken part in 126 matches so far. The red card rate of the Super League is 0.3."
        }]
        export const Matches_3 = [
            {
                id:1,
                match_id:3,
                first_name:"Arda Kardeşler",
                age :34,
                birthdate:"03.01.1988",        
                image: "1.jpg", 
                match_count: "8",
                rating:"874",
                Yellow_Card:29,
                Red_Card:1,
                Penalty:2,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"The son of former Bursaspor national goalkeeper Eser Kardeşler, Arda Kardeşler is also the brother of goalkeeper Erce Kardeşler. He started his refereeing career in 2009. He made his professional debut on September 1, 2013. He has been in the Süper Lig since the 2015-2016 season."
            },
            {
                id:2,
                match_id:3,
                first_name:"Volkan Bayarslan",
                age:44, 
                birthdate:"01.01.1978",
                image: "2.jpg", 
                match_count: "7",
                rating:"764",
                Yellow_Card:26,
                Red_Card:0,
                Penalty:2,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Volkan Bayarslan (born 1 January 1978, Erzurum) Turkish referee. He played in the Bursaspor - Manisaspor match for the first time in the Super League. He played football in Erzurumspor's youth team. He was transferred to Ağrı Spor when he was in the 3rd year of Karadeniz Technical University. He quit professional football in 1999 and started refereeing. Later, 37-year-old Bayarslan, who moved to Istanbul with his family, successfully rose in the classification with the contribution of his strong physical structure and football knowledge, and started to manage matches in the Super League. "
            },
            {
                id:3,
                match_id:3,
                first_name:"Yaşar Kemal Uğurlu",
                age:41,
                birthdate:"1981",
                image: "3.jpg", 
                match_count: "7",
                rating:"563",
                Yellow_Card:37,
                Red_Card:0,
                Penalty:5,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Yaşar Kemal Uğurlu was born in Ankara in 1981. He started his refereeing career in 2004 with the refereeing course he attended in Düzce in 2002. Uğurlu, who plays football in various categories of the Ankaragücü team, is a graduate of Gazi University, department of economics. Yaşar Kemal Uğurlu decided to become a referee after he did not like the referee's decisions after watching a match."
            },
            {
                id:4,
                match_id:3,
                first_name:"Mert Güzenge",
                age:31,
                birthdate:"1990", 
                image: "4.jpeg", 
                match_count:"7", 
                rating:"435",
                Yellow_Card:29,
                Red_Card:0,
                Penalty:1,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Mert Güzenge, from Istanbul, is the top-class referee. Mert Güzenge, whose main profession is a manager, also continues to act as a referee."
            },
            {
                id:5,
                match_id:3,
                first_name:"Abdulkadir Bitigen",
                age:39,
                birthdate:"12.02.1983",
                image: "5.jpg", 
                match_count: "6",
                rating:"434",
                Yellow_Card:31,
                Red_Card:1,
                Penalty:2,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"He started refereeing in 2007. The first match he directed in the Super League was Eskişehirspor - Konyaspor (2014). His father, Galip Bitigen, was also a football referee."
            },
            {
                id:6,
                match_id:3,
                first_name:"Umit Öztürk",
                age:39,
                birthdate:"1983", 
                image: "6.jpg", 
                match_count: "6",
                rating:"544",
                Yellow_Card:33,
                Red_Card:0,
                Penalty:4,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Referee Ümit Öztürk was born in the Şişli district of Istanbul in 1983. Originally from Ordu, the 39-year-old referee studied geological engineering at Karadeniz Technical University. He decided to become a referee in his last year of university."
            },
            {
                id:7,
                match_id:3,
                first_name:"Bahattin Şimşek",
                age:32,
                birthdate:"1988",
                image: "7.jpg", 
                match_count: "6",
                rating:"334",
                Yellow_Card:16,
                Red_Card:2,
                Penalty:0,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Bahattin Şimşek, one of the successful Turkish referees who was born in 1988, stepped into the refereeing profession in 2006. Şimşek, who managed his first professional match on September 9, 2012, is a graduate of Adnan Menderes University, School of Physical Education and Sports."
            },
            {
                id:8,
                match_id:3,
                first_name:"Mustafa Kürşad Filiz",
                age:29,
                birthdate:"1993",
                image: "8.jpg", 
                match_count: "6",
                rating:"333",
                Yellow_Card:24,
                Red_Card:0,
                Penalty:1,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Mustafa Kürşat Filiz is an Istanbul regional referee, born in 1993. He whistled in 96 matches in total."
            },
            {
                id:9,
                match_id:3,
                first_name:"Kadir Sağlam",
                age:35,
                birthdate:"1987",
                image: "9.jpg", 
                match_count: "6",
                rating:"434",
                Yellow_Card:31,
                Red_Card:1,
                Penalty:3,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Kadir Sağlam, born in 1987, is the Ankara regional referee. He took part in 130 matches in total. Kadir Sağlam, who usually serves as the 4th referee, started playing as the middle referee last year."
            },
            {
                id:10,
                match_id:3,
                first_name:"Ali Şansalan",
                age:34,
                birthdate:"17.03.1988",
                image: "10.jpg", 
                match_count: "6",
                rating:"764",
                Yellow_Card:36,
                Red_Card:0,
                Penalty:6,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Ali Şansalan (born 17 March 1988, Balıkesir) is a Turkish professional football referee in the Süper Lig. He graduated from Çanakkale Onsekiz Mart University Faculty of Sports Sciences in 2010. He started refereeing in 2009 as a Çanakkale regional referee while he was still a university student. In the fight between Akhisar Belediyespor and Kardemir Karabükspor in 2017, Şansalan has been playing a regular role in the Super League since 2019, leading the game for the first time in the Super League."
            },
            {
                id:11,
                match_id:3,
                first_name:"Atilla Karaoğlan",
                age:36,
                birthdate:"22.06.1986",
                image: "11.jpg", 
                match_count: "6",
                rating:"646",
                Yellow_Card:26,
                Red_Card:0,
                Penalty:2,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"He was born on June 22, 1986 in Sakarya. Atilla Karaoğlan, who started his refereeing career in 2007, has been managing matches in the Super League since the 2019-2020 season."
            },
            {
                id:12,
                match_id:3,
                first_name:"Zorbay Küçük",
                age:30,
                birthdate:"14.09.1992",
                image: "12.jpg", 
                match_count: "6",
                rating:"858",
                Yellow_Card:26,
                Red_Card:0,
                Penalty:2,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Zorbay Küçük was born in Adana on October 18, 1992. Zorbay Küçük is the son of former football player and coach Feyzullah Küçük. He started refereeing in 2010."
            },
            {
                id:13,
                match_id:3,
                first_name:"Hüseyin Göcek",
                age:45,
                birthdate:"30.11.1976",
                image: "13.jpg", 
                match_count: "5",
                rating:"757",
                Yellow_Card:30,
                Red_Card:0,
                Penalty:1,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Assigned by UEFA in high-level competitions, he served as the 4th referee in the fight between Greece and Russia, which is one of the Euro 2012 group qualifying matches, as the line referee in the fights between Ireland-Italy, Ukraine-Sweden and Spain-Portugal in the semi-finals. Hüseyin Göçek managed the 2014 Turkish Cup Final, played on 7 May 2014 between Galatasaray and Eskişehirspor.[5] With this match, he was appointed as the cup final referee for the first time. Before the 2015-16 season, Turkish Football Federation signed a professional contract for the first time with 9 referees, including Göçek"
            },
            {
                id:14,
                match_id:3,
                first_name:"Suat Arslanboğa",
                age:44,
                birthdate:"04.06.1978",
                image: "14.jpg", 
                match_count: "5", 
                rating:"985",
                Yellow_Card:33,
                Red_Card:0,
                Penalty:2,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"He started as an assistant referee in the away league in 2001. In the Super League, he played his first match in the Bursaspor - Hacettepe match on October 6, 2007. In this match, he showed 6 players from Bursaspor and 2 players from Hacettepespor a yellow card and a red card to İlhan Eker from Hacettepespor. The match ended 1-1 with mutual goals from Mustafa Sarp and Bülent Kocabey."
            },
            {
                id:15,
                match_id:3,
                first_name:"Mete Kalkavan",
                age:42,
                birthdate:"1980",
                image: "15.jpg", 
                match_count: "5", 
                rating:"985",
                Yellow_Card:19,
                Red_Card:2,
                Penalty:3,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Mete Kalkavan is a Turkish football referee and mechanical engineer. He graduated with a successful degree in the TFF Refereeing course he attended. His first match in 1999 was the Istanbulspor - Altay match played as the 1st assistant referee in the PAF League. He still serves as the Super League referee. 24 December He earned the right to wear a FIFA badge in 2012. He signed a professional contract for the first time with 9 referees, including Turkish Football Federation Kalkavan, before the 2015-16 season. He resigned from refereeing on March 9, 2022 and returned to refereeing on May 1, 2022."
            },
            {
                id:16,
                match_id:3,
                first_name:"Ali Palabıyık",
                age:41,
                birthdate:"14.08.1981",
                image: "16.jpg", 
                match_count: "5", 
                rating:"476",
                Yellow_Card:24,
                Red_Card:5,
                Penalty:6,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Ali Palabıyık (born 14 August 1981, Ankara) is a Turkish football referee with FIFA license. He was among the referees who will wear the FIFA badge announced for 2015 for the first time. Before the 2015-16 season, Turkish Football Federation signed a professional contract for the first time with 9 referees, including Palabiyik."
            },
            {
                id:17,
                match_id:3,
                first_name:"Sarper Barış Saka",
                age:39,
                birthdate:"24.10.1983",
                image: "17.jpg", 
                match_count: "5", 
                rating:"235",
                Yellow_Card:22,
                Red_Card:1,
                Penalty:0,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Sarper Barış Saka was born in Antalya in 1983, he is the Ankara regional referee. He took part in 129 matches in total."
            },
            {
                id:18,
                match_id:3,
                first_name:"Çağdaş Altay",
                age:"-",
                birthdate:"-",
                image: "18.jpg", 
                match_count: "5", 
                rating:"647",
                Yellow_Card:21,
                Red_Card:2,
                Penalty:3,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Contemporary Altay is the Istanbul regional referee. He took part in 112 matches in total."
            },
            {
                id:19,
                match_id:3,
                first_name:"Tugay Kaan Numanoğlu",
                age:37,
                birthdate:"06.11.1985",
                image: "19.jpg", 
                match_count: "4", 
                rating:"758",
                Yellow_Card:17,
                Red_Card:1,
                Penalty:2,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Referee Tugay Kaan Numanoğlu, born on November 6, 1985, is 37 years old today. He started his refereeing career in 2006 when he was 21 years old. Tugay Kaan Numanoğlu, who started to manage the Super League matches in 2020, was involved in various matches of the lower leagues before that."
            },
            {
                id:20,
                match_id:3,
                first_name:"Halil Umut Beler",
                age:36,
                birthdate:"01.08.1986",
                image: "20.jpg", 
                match_count: "4", 
                rating:"875",
                Yellow_Card:24,
                Red_Card:0,
                Penalty:0,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Halil Umut Meler is a Turkish football referee. He has been FIFA listed since 2017 and a member of the UEFA Elite since 2022. He has officiated in 2017–18 UEFA Europa League, beginning with the match between Vojvodina and Ružomberok on 29 June 2017 "
            },
            {
                id:21,
                match_id:3,
                first_name:"Erkan Özdamar",
                age:34,
                birthdate:"1988",
                image: "21.jpg", 
                match_count: "4", 
                rating:"875",
                Yellow_Card:24,
                Red_Card:0,
                Penalty:0,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Erkan Özdamar, who is a dance instructor, has international Sports and Dance Instructor certificates. Erkan Özdamar, one of the referees of the Ankara region of the TFF, started to be assigned as a referee in the Super League in the 2020-2021 season. Erkan Özdamar, in 15 matches he directed, 65 yellows, 1 second. He took out 2 red cards, one of the yellow ones."
            },
            {
                id:22,
                match_id:3,
                first_name:"Burak Şeker",
                age:33,
                birthdate:"1989", 
                image: "22.jpg", 
                match_count: "3", 
                rating:"675",
                Yellow_Card:15,
                Red_Card:1,
                Penalty:3,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Burak Şeker is an Antalya regional referee, born in 1989. He has taken part in 122 matches so far."
            },
            {
                id:23,
                match_id:3,
                first_name:"Yasin Kol",
                age:34,
                birthdate:"15.12.1987",
                image: "23.jpg", 
                match_count: "3", 
                rating:"766",
                Yellow_Card:13,
                Red_Card:0,
                Penalty:2,
                hometeam:"Beşiktaş",
                againstteam:"Adana Demirspor",
                date:"29/12/2022",
                info:"Yasin Kol, born in Trabzon in 1987, is a Trabzon regional referee. He has taken part in 126 matches so far. The red card rate of the Super League is 0.3."
            }]